kind: pipeline
type: docker
name: CI/CD LPTDPA Administration

trigger:
  event:
    - push
  branch:
    - master

steps:
  - name: install_dependencies
    image: composer:latest
    commands:
      - composer install --no-interaction --prefer-dist --optimize-autoloader

  - name: copy_env_file
    image: php:8.2
    commands:
      - cp .env.example .env

  - name: generate_app_key
    image: php:8.2
    commands:
      - php artisan key:generate

  - name: run_migrations
    image: php:8.2
    environment:
      MYSQL_DATABASE:
        from_secret: mysql_database
      MYSQL_USER:
        from_secret: mysql_user
      MYSQL_PASSWORD:
        from_secret: mysql_password
    commands:
      - php artisan migrate --force

  # - name: run_tests
  #   image: php:8.2
  #   commands:
  #
  #     - ./vendor/bin/phpunit

  - name: connect_ssh
    image: alpine
    environtment:
      username:
        from_secret: SSH_USERNAME
    commands:
      - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
      - chmod 600 ~/.ssh/id_ed25519
      - ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no $username@149.129.195.54 "echo 'SSH connection successful'"

  - name: deploy
    image: appleboy/drone-ssh
    environment:
      SSH_PRIVATE_KEY:
        from_secret: SSH_PRIVATE_KEY
    settings:
      host: 149.129.195.54
      username:
        from_secret: SSH_USERNAME
      port: 22
      private_key:
        from_secret: SSH_PRIVATE_KEY
      script:
        - if [ ! -d "/var/www/html/LAD/.git" ]; then
          rm -rf /var/www/html/LAD;
          git clone https://github.com/mhenryaditya/LAD.git /var/www/html/LAD;
          else
          cd /var/www/html/LAD;
          git pull origin master;
          fi
        - cd /var/www/html/LAD
        - export COMPOSER_ALLOW_SUPERUSER=1
        - composer install --no-interaction --prefer-dist --optimize-autoloader
        - php artisan migrate --force
        - php artisan cache:clear
        - php artisan config:clear
        - php artisan config:cache
        - php artisan route:clear
        - php artisan view:cache
